"""Initial migration

Revision ID: 4255eb989fc6
Revises: 
Create Date: 2025-03-10 00:19:17.636495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4255eb989fc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_option', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('paybill_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('till_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('till_number')
        batch_op.drop_column('paybill_number')
        batch_op.drop_column('payment_option')

    # ### end Alembic commands ###
